/* ============================================================
   data.js — 메뉴/카테고리 시드 데이터
   ------------------------------------------------------------
   현재: 정적 시드 데이터를 localStorage에 최초 1회 주입.
   추후: 8단계 이후 Supabase 테이블로 대체 (필드 구조 그대로 매핑 가능).
   ============================================================ */

/* 카테고리: id는 메뉴의 categoryId와 매칭 */
const SEED_CATEGORIES = [
  { id: "coffee", name: "커피", emoji: "☕" },
  { id: "tea", name: "티/논커피", emoji: "🍵" },
  { id: "ade", name: "에이드/주스", emoji: "🥤" },
  { id: "dessert", name: "디저트", emoji: "🍰" },
];

/* 메뉴
   필드: id, categoryId, name, description, price, emoji,
        imageUrl(루트 기준 상대경로), gradient(이미지 로드 실패 시 배경),
        badges(추천/신메뉴 등), soldOut, createdAt
   price 단위: 원(KRW) */
const SEED_MENUS = [
  {
    id: "m-001",
    categoryId: "coffee",
    name: "아메리카노",
    description: "깊고 진한 에스프레소에 물을 더한 클래식 커피. HOT / ICE 선택 가능.",
    price: 4000,
    emoji: "☕",
    imageUrl: "assets/menus/m-001.jpg",
    gradient: "linear-gradient(135deg, #d7bfa6, #6f4e37)",
    badges: ["인기"],
    soldOut: false,
    createdAt: "2026-06-01T09:00:00.000Z",
  },
  {
    id: "m-002",
    categoryId: "coffee",
    name: "카페라떼",
    description: "부드러운 스팀 우유와 에스프레소의 조화. 고소하고 부드러운 맛.",
    price: 4500,
    emoji: "🥛",
    imageUrl: "assets/menus/m-002.jpg",
    gradient: "linear-gradient(135deg, #f3e9dd, #c8a27c)",
    badges: ["인기"],
    soldOut: false,
    createdAt: "2026-06-01T09:05:00.000Z",
  },
  {
    id: "m-003",
    categoryId: "coffee",
    name: "바닐라 라떼",
    description: "바닐라 시럽의 은은한 단맛이 더해진 라떼.",
    price: 5000,
    emoji: "🍦",
    imageUrl: "assets/menus/m-003.jpg",
    gradient: "linear-gradient(135deg, #faf4ec, #b07d52)",
    badges: [],
    soldOut: false,
    createdAt: "2026-06-02T09:00:00.000Z",
  },
  {
    id: "m-004",
    categoryId: "coffee",
    name: "카푸치노",
    description: "풍성한 우유 거품이 매력적인 이탈리안 클래식.",
    price: 4800,
    emoji: "☕",
    imageUrl: "assets/menus/m-004.jpg",
    gradient: "linear-gradient(135deg, #e8d5bf, #8a6d54)",
    badges: [],
    soldOut: true,
    createdAt: "2026-06-02T09:10:00.000Z",
  },
  {
    id: "m-005",
    categoryId: "tea",
    name: "캐모마일 티",
    description: "은은한 향의 캐모마일로 편안한 휴식을.",
    price: 4500,
    emoji: "🌼",
    imageUrl: "assets/menus/m-005.jpg",
    gradient: "linear-gradient(135deg, #f6efd8, #cdae6d)",
    badges: [],
    soldOut: false,
    createdAt: "2026-06-03T09:00:00.000Z",
  },
  {
    id: "m-006",
    categoryId: "tea",
    name: "그린 티 라떼",
    description: "진한 말차와 부드러운 우유가 어우러진 라떼.",
    price: 5200,
    emoji: "🍵",
    imageUrl: "assets/menus/m-006.jpg",
    gradient: "linear-gradient(135deg, #dfe9cf, #7f9b5a)",
    badges: ["신메뉴"],
    soldOut: false,
    createdAt: "2026-06-10T09:00:00.000Z",
  },
  {
    id: "m-007",
    categoryId: "ade",
    name: "자몽 에이드",
    description: "상큼한 자몽과 탄산의 청량한 조화.",
    price: 5500,
    emoji: "🍊",
    imageUrl: "assets/menus/m-007.jpg",
    gradient: "linear-gradient(135deg, #ffe3d0, #e8895f)",
    badges: ["인기"],
    soldOut: false,
    createdAt: "2026-06-04T09:00:00.000Z",
  },
  {
    id: "m-008",
    categoryId: "ade",
    name: "청포도 에이드",
    description: "달콤한 청포도의 향긋함이 가득.",
    price: 5500,
    emoji: "🍇",
    imageUrl: "assets/menus/m-008.jpg",
    gradient: "linear-gradient(135deg, #e3efc9, #9bbf5a)",
    badges: ["신메뉴"],
    soldOut: false,
    createdAt: "2026-06-11T09:00:00.000Z",
  },
  {
    id: "m-009",
    categoryId: "dessert",
    name: "티라미수",
    description: "마스카포네 치즈와 에스프레소가 어우러진 이탈리안 디저트.",
    price: 6000,
    emoji: "🍰",
    imageUrl: "assets/menus/m-009.jpg",
    gradient: "linear-gradient(135deg, #f0e0cd, #a97e56)",
    badges: ["인기"],
    soldOut: false,
    createdAt: "2026-06-05T09:00:00.000Z",
  },
  {
    id: "m-010",
    categoryId: "dessert",
    name: "치즈케이크",
    description: "꾸덕하고 진한 뉴욕 스타일 치즈케이크.",
    price: 6500,
    emoji: "🧀",
    imageUrl: "assets/menus/m-010.jpg",
    gradient: "linear-gradient(135deg, #fff0d4, #e6c15c)",
    badges: [],
    soldOut: false,
    createdAt: "2026-06-06T09:00:00.000Z",
  },
  {
    id: "m-011",
    categoryId: "dessert",
    name: "초코 브라우니",
    description: "진한 다크초콜릿의 풍미가 가득한 브라우니.",
    price: 5000,
    emoji: "🍫",
    imageUrl: "assets/menus/m-011.jpg",
    gradient: "linear-gradient(135deg, #d8bfa8, #5a3d2b)",
    badges: [],
    soldOut: false,
    createdAt: "2026-06-07T09:00:00.000Z",
  },
  {
    id: "m-012",
    categoryId: "coffee",
    name: "콜드브루",
    description: "12시간 저온 추출로 부드럽고 깊은 풍미.",
    price: 5000,
    emoji: "🧊",
    imageUrl: "assets/menus/m-012.jpg",
    gradient: "linear-gradient(135deg, #cbb79f, #4a3320)",
    badges: ["신메뉴"],
    soldOut: false,
    createdAt: "2026-06-12T09:00:00.000Z",
  },
];

/* 전역 노출 (모듈 번들러 없이 <script>로 로드하는 구조) */
window.CAFE_SEED = {
  categories: SEED_CATEGORIES,
  menus: SEED_MENUS,
};
